//server component
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from 'next/image';
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChartLine, faFileLines, faRightFromBracket } from "@fortawesome/free-solid-svg-icons";
import LogoutButton from "@/components/buttons/LogoutButton";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect('/');
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-blue-100 w-48 p-4">
            <div className="rounded-full overflow-hidden 
            aspect-square w-24 mx-auto">
              <Image src={session.user.image} width={256} height={128}
                alt={'avatar'} />
            </div>
            <div className="text-center ">
              <nav className="inline-flex flex-col text-center mt-12 
            gap-6 text-gray-700">
                <Link href={'/account'} className="flex gap-4
              ">
                  <FontAwesomeIcon
                    fixedWidth={true}
                    icon={faFileLines}
                    className={"w-6 h-6"} />
                  <span className="text-gray-700">My Page</span>
                </Link>
                <Link href={'/analytics'} className="flex gap-4
              ">
                  <FontAwesomeIcon
                    fixedWidth={true}
                    icon={faChartLine}
                    className={"w-6 h-6"}
                  />
                  <span className="">Analytics</span>
                </Link>
                <LogoutButton 
                iconLeft={true} 
                className={"flex gap-4 items-center text-gray-700"}
                iconClasses = {'w-6 h-6'}
                />
              </nav>
              </div>
          </aside>
          <div className="max-w-4xl mx-auto p-6">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
